### ISSUE TITLE
Migrate to Axum | v1.0.0

### ISSUE THREAD

**Issue by LeoBorai** [http-server-rs/http-server#313]
## Roadmap

The following list includes all todos to complete migration, on `main` branch we still have Hyper version running which
is tagged as `v0.x`.

- [x] Debug/Tracing Logging (Debugging)
    - [x] https://github.com/http-server-rs/http-server/issues/286
    - [x] https://github.com/http-server-rs/http-server/pull/291
- [x] #314
- [x] #315
  - [ ] Modified Date
  - [ ] File Size
  - [ ] Breadcrumb Navigation
  - [ ] File Upload
  - [ ] Filtering
  - [ ] Sorting
    - [ ] Sort By: File Name
    - [ ] Sort By: File Size
    - [ ] Sort By: File Modified Date
    - [ ] Directories First
    - [ ] Files First
- [x] #316
  - [ ] HTTPS/TLS Support
- [x] #317
  - [ ] `gzip/deflate` Compression
  - [ ] `brotli` Compression
- [x] #318
  - [ ] Cross Origin Resource Sharing
    - [ ] Allow Credentials
    - [ ] Allow Headers
    - [ ] Allow Methods
    - [ ] Allow Origin
    - [ ] Expose Headers
    - [ ] Max Age
    - [ ] Request Headers
    - [ ] Request Methods
    - [ ] Multiple Origins
- [x] #319
  - [ ] `Last-Modified` and `ETag`
  - [ ] Respond with 304 to `If-Modified-Since`
- [x] #320
  - [ ] `Accept-Ranges`
  - [ ] `Content-Range`
  - [ ] `If-Range`
  - [ ] `If-Match`
  - [ ] `Range`
- [x] #321
  - [ ] macOS
  - [ ] Linux
  - [ ] Windows
- [x] #322
  - [ ] Live Reload
- [x] #323
  - [ ] URL Configuration
- [x] #324
  - [ ] Username
  - [ ] Password
- [ ] Graceful Shutdown
